import Head from 'next/head';
import styles from '@/styles/Create.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>D&D Character Creator | Create new character</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <div className={styles.create__topbar}>
          <ul>
            <li>1. Race</li>
            <li>2. Class</li>
            <li>3. Abilities</li>
            <li>4. Description</li>
            <li>5.Equipment</li>
          </ul>
        </div>
      </div>
    </>
  )
}