import Head from 'next/head';
import styles from '@/styles/auth/Login.module.scss';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";
import { getProviders, getSession, signIn } from 'next-auth/react';

type FormData = {
    password: string;
    username: string;
};

const schema = yup.object({
    username: yup.string().required(),
    password: yup.string().required(),
}).required();

export default function Login() {
    const { register, handleSubmit, watch, formState: { errors } } = useForm<FormData>({resolver: yupResolver(schema)});
    const onSubmit = (data: FormData) => {
        signIn("credentials", {
            username: data.username,
            password: data.password
        });
    };
  
    return (
        <>
            <Head>
                <title>D&D Character Creator | Login</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <div>
                    <form onSubmit={handleSubmit(onSubmit)} className={styles.form}>
                        <div className={styles.form__row}>
                            <label className={styles.form__label}>Username</label>
                            <input {...register("username")} className={styles.form__input}></input>
                        </div>
                        <p>{errors.username?.message}</p>
                        <div className={styles.form__row}>
                            <label className={styles.form__label}>Password</label>
                            <input type="password" {...register("password")} className={styles.form__input}></input>
                        </div>
                        <p>{errors.password?.message}</p>
                        <button type="submit" className={`${styles.btn} ${styles.primary}`}>
                            Login
                        </button>
                        <p>Don't have an account yet? Register</p>
                    </form>
                </div>
            </div>
        </>
    )
}

export async function getServerSideProps(context: any) {
    const { req } = context;
    const session = await getSession({ req });
    const providers = await getProviders()

    if (session) {
        return {
            redirect: { destination: '/' }
        };
    }

    return {
        props: {
            providers
        }
    }
}