import Head from 'next/head';
import { useRouter } from 'next/router';
import styles from '@/styles/auth/Auth.module.scss';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from "yup";
import { Roboto_Condensed } from 'next/font/google';

type FormData = {
    username: string;
    name: string;
    email: string;
    password: string;
    passwordConfirmation: string;
};

const roboto = Roboto_Condensed({
    subsets: ['latin'],
    weight: ['400', '700']
});

const schema = yup.object({
    username: yup.string().required(),
    name: yup.string().required(),
    email: yup.string().email().required(),
    password: yup.string().required(),
    passwordConfirmation: yup.string().required().oneOf([yup.ref('password')], 'Passwords must match'),
}).required();

export default function Login() {
    const { register, handleSubmit, watch, formState: { errors } } = useForm<FormData>({resolver: yupResolver(schema)});
    const router = useRouter();
    const onSubmit = async (data: FormData) => {
        const res = await fetch("http://localhost:3001/api/users/register", {
            method: 'POST',
            headers: {
                "Content-Type": "application/json",    
            },
            body: JSON.stringify(data)
        });

        const user = await res.json();
        if (res.ok && user) {
            router.push('/auth/login');
        };
        return null;
    };
  
    return (
        <>
            <Head>
                <title>D&D Character Creator | Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <div className={styles.auth}>
                    <h2 className={styles.header}>Register</h2>
                    <form onSubmit={handleSubmit(onSubmit)} className={styles.form}>
                        <div className={styles.form__image}>

                        </div>
                        <div className={styles.form__content}>
                            <div className={styles.form__data}>
                                <div className={styles.form__row}>
                                    <label className={styles.form__label}>Username</label>
                                    <input {...register("username")} className={styles.form__input}></input>
                                </div>
                                <p>{errors.username?.message}</p>
                                <div className={styles.form__row}>
                                    <label className={styles.form__label}>Name</label>
                                    <input {...register("name")} className={styles.form__input}></input>
                                </div>
                                <p>{errors.name?.message}</p>
                                <div className={styles.form__row}>
                                    <label className={styles.form__label}>Email</label>
                                    <input {...register("email")} className={styles.form__input}></input>
                                </div>
                                <p>{errors.email?.message}</p>
                                <div className={styles.form__row}>
                                    <label className={styles.form__label}>Password</label>
                                    <input type="password" {...register("password")} className={styles.form__input}></input>
                                </div>
                                <p>{errors.password?.message}</p>
                                <div className={styles.form__row}>
                                    <label className={styles.form__label}>Password</label>
                                    <input type="password" {...register("passwordConfirmation")} className={styles.form__input}></input>
                                </div>
                            </div>
                            <div className={styles.form__buttons}>
                                <p>{errors.passwordConfirmation?.message}</p>
                                <button type="submit" className={`${styles.btn} ${styles.primary} ${roboto.className}`}>
                                    Submit
                                </button>
                                <p>Already have an account yet? Login</p>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </>
    )
}