import Head from "next/head";
import { useCharacterStore } from "@/store";
import type {
  AbilityScores,
  ApiClass,
  ApiRace,
  Background,
  Equipment,
  Skills,
  Spell,
  CharacterDescription,
  Spells,
} from "@/types";
import styles from "@/styles/Character.module.scss";
import { useSession } from "next-auth/react";
import { calculateAbilityModifier, calculateProfBonus } from "@/utils";

export default function CharacterSheet(): JSX.Element {
  const race: ApiRace = useCharacterStore((state) => state.race);
  const dndClass: ApiClass = useCharacterStore((state) => state.dndClass);
  const abilities: AbilityScores = useCharacterStore(
    (state) => state.abilityScores
  );
  const background: Background = useCharacterStore((state) => state.background);
  const description: CharacterDescription = useCharacterStore(
    (state) => state.description
  );
  const skills: Skills = useCharacterStore((state) => state.skills);
  const equipment: Equipment[] = useCharacterStore((state) => state.equipment);
  const spells: Spells = useCharacterStore((state) => state.spells);
  const level: number = useCharacterStore((state) => state.level);
  const experience: number = useCharacterStore((state) => state.experience);
  const gold: number = useCharacterStore((state) => state.gold);
  const { data: session, status } = useSession();

  return (
    <>
      <Head>
        <title>D&D Character Creator | Character Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.characterSheet}>
        <div className={styles.characterSheet__intro}>
          <div>
            <h2>{description.details.name}</h2>
          </div>
          <div className={styles.characterSheet__details}>
            <div>
              <div>
                {dndClass.name}
                <span>{level}</span>
              </div>
              <div>{background.name}</div>
            </div>
            <div>
              <div>{race.name}</div>
              <div>{description.details.alignment}</div>
            </div>
            <div>
              <div>{session?.user?.name}</div>
              <div>{experience}</div>
            </div>
          </div>
        </div>
        <div className={styles.characterSheet__main}>
          <div className={styles.characterSheet__main__left}>
            <div>
              {Object.entries(abilities).map(
                ([key, value]): JSX.Element => (
                  <div key={key}>
                    <div>{key}</div>
                    <div>{value}</div>
                  </div>
                )
              )}
            </div>
            <div>
              <div>
                <div className={styles.characterSheet__main__left__area}>
                  <div>Proficiency Bonus</div>
                  <div>{calculateProfBonus(level)}</div>
                </div>
                <div className={styles.characterSheet__main__left__area}>
                  <div>Saving Throws</div>
                  <div>
                    {Object.entries(abilities).map(
                      ([key, value]): JSX.Element => (
                        <div
                          key={key}
                          className={styles.characterSheet__main__left__flex}
                        >
                          {dndClass.proficiencies?.filter(
                            (prof: any): boolean =>
                              prof.name.substring(14) === key
                          )?.length ? (
                            <div className={styles.filledDot}></div>
                          ) : (
                            <div className={styles.dot}></div>
                          )}
                          <div>{key}</div>
                          <div>
                            {dndClass.proficiencies?.filter(
                              (prof: any): boolean =>
                                prof.name.substring(14) === key
                            )?.length
                              ? calculateAbilityModifier(value) +
                                calculateProfBonus(level)
                              : calculateAbilityModifier(value)}
                          </div>
                        </div>
                      )
                    )}
                  </div>
                </div>
                <div className={styles.characterSheet__main__left__area}>
                  <div>Skills</div>
                  <div>
                    {Object.entries(skills).map(
                      ([key, { name, value, modifier }]): JSX.Element => (
                        <div
                          key={key}
                          className={styles.characterSheet__main__left__flex}
                        >
                          {value ? (
                            <div className={styles.filledDot}></div>
                          ) : (
                            <div className={styles.dot}></div>
                          )}
                          <div>{name}</div>
                          <div>
                            {value
                              ? calculateProfBonus(level) +
                                calculateAbilityModifier(
                                  (abilities as any)[modifier]
                                )
                              : calculateAbilityModifier(
                                  (abilities as any)[modifier]
                                )}
                          </div>
                        </div>
                      )
                    )}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div>
          <div>
            <div>Spellcasting Ability</div>
            <div>
              {calculateAbilityModifier(
                (abilities as any)[
                  dndClass.spellcasting?.spellcasting_ability.name
                ]
              )}
              <span>({dndClass.spellcasting?.spellcasting_ability.name})</span>
            </div>
          </div>
        </div>
        <div></div>
      </div>
    </>
  );
}
