import Head from "next/head";
import { getSession } from "next-auth/react";
import styles from "@/styles/Dashboard.module.scss";
import { Character } from "@/types";
import { GetServerSideProps } from "next";
import CharacterList from "@/features/characters/CharacterList";

interface Props {
  characters: Array<Character>;
}

export default function Dashboard({
  characters,
}: {
  characters: Array<Character>;
}) {
  return (
    <>
      <Head>
        <title>D&D Character Creator | Character Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.dashboard}>
        <div>
          <h2>Dashboard</h2>
          <section>
            <CharacterList characters={characters} />
          </section>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<Props> = async (
  context
) => {
  const session = await getSession(context);
  let characters: Array<Character> = [];

  try {
    const res = await fetch(
      `http://localhost:3001/api/users/${session?.user?.user.id}/characters`
    );
    const result = await res.json();
    characters = result.characters;
  } catch (err) {
    console.error(err);
  }

  return {
    props: {
      characters,
    },
  };
};
