import Head from "next/head";
import { useSession } from "next-auth/react";
import styles from "@/styles/Dashboard.module.scss";
import { Character } from "@/types";

export default function Dashboard() {
  const { data: session, status } = useSession();
  console.log(session?.user);
  return (
    <>
      <Head>
        <title>D&D Character Creator | Character Sheet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.characterSheet}>
        <div>
          <h2>Dashboard</h2>
          <section></section>
        </div>
      </main>
    </>
  );
}
