import Head from "next/head";
import withTypeWriterEffect from "@/components/TypewriterEffect";
import withAnimatedBorder from "@/components/withAnimatedBorder";
import styles from "@/styles/Home.module.scss";
import { ReactNode } from "react";

interface Props {
  children: ReactNode;
}

export default function Home() {
  const Card = ({ children }: Props) => (
    <div className={styles.card}>
      <h2 className={styles.header}>{children}</h2>
    </div>
  );
  const TypeWriterText = withTypeWriterEffect(Card);

  return (
    <>
      <Head>
        <title>D&D Character Creator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TypeWriterText>Create, Level Up, Store, Manage.</TypeWriterText>
      </main>
    </>
  );
}
