import { ReactNode } from "react";
import Head from "next/head";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faUser,
  faUserShield,
  faUsers,
  faUserPlus,
} from "@fortawesome/free-solid-svg-icons";
import withTypeWriterEffect from "@/features/ui/TypewriterEffect";
import Hero from "@/features/ui/Hero";
import styles from "@/styles/Home.module.scss";
import { useSession } from "next-auth/react";

interface Props {
  children: ReactNode;
}

export default function Home() {
  const { data: session, status } = useSession();
  const Header = ({ children }: Props) => (
    <div className={styles.card}>
      <h2 className={styles.header}>{children}</h2>
    </div>
  );
  const HeaderWithTypeWriterEffect = withTypeWriterEffect(Header);

  return (
    <>
      <Head>
        <title>D&D Character Creator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.home}>
        <Hero>
          <HeaderWithTypeWriterEffect>
            Create, Level Up, Store, Manage.
          </HeaderWithTypeWriterEffect>
        </Hero>
        <div className={styles.features__wrapper}>
          <div className={styles.features}>
            <div className={styles.features__card}>
              <div className={styles.features__card__icon}>
                <FontAwesomeIcon icon={faUser} />
              </div>
              <h2>Create</h2>
              <p>
                Create your D&D 5th edition characters with a robust character
                creator.
              </p>
            </div>
            <div className={styles.features__card}>
              <div className={styles.features__card__icon}>
                <FontAwesomeIcon icon={faUserPlus} />
              </div>
              <h2>Level</h2>
              <p>
                Level up your characters and adjust hitpoints and choose your
                ASIs.
              </p>
            </div>
            <div className={styles.features__card}>
              <div className={styles.features__card__icon}>
                <FontAwesomeIcon icon={faUserShield} />
              </div>
              <h2>Store</h2>
              <p>Save your characters so you can revisit them later.</p>
            </div>
            <div className={styles.features__card}>
              <div className={styles.features__card__icon}>
                <FontAwesomeIcon icon={faUsers} />
              </div>
              <h2>Manage</h2>
              <p>
                Manage all your characters: delete them, edit them or just check
                them out in greater detail.
              </p>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
